export const books = [
    {
        ISBN: "978-0-345-49149-4",
        name: "The Maze Runner",
        description:
            "The first book in The Maze Runner series by James Dashner, following Thomas, a boy who wakes up in a mysterious maze with no memory of his past, and his attempts to escape.",
        price: 8.99,
        author: "James Dashner",
        genre: "Action",
        publisher: "Delacorte Press",
        yearPublished: 2009,
        copiesSold: 1000000,
    },
    {
        ISBN: "978-0-618-25760-4",
        name: "The Name of the Wind",
        description:
            "A fantasy novel by Patrick Rothfuss that tells the story of Kvothe, a magically gifted young man, as he grows to be the most notorious wizard his world has ever seen.",
        price: 10.99,
        author: "Patrick Rothfuss",
        genre: "Fantasy",
        publisher: "DAW Books",
        yearPublished: 2007,
        copiesSold: 1000000,
    },
    {
        ISBN: "978-0-316-07762-3",
        name: "The Shining",
        description:
            "A horror novel by Stephen King that follows Jack Torrance, an aspiring writer and recovering alcoholic, who becomes the winter caretaker of the Overlook Hotel, where supernatural forces drive him to madness.",
        price: 12.99,
        author: "Stephen King",
        genre: "Horror",
        publisher: "Doubleday",
        yearPublished: 1977,
        copiesSold: 4000000,
    },
    {
        ISBN: "978-0-399-14520-0",
        name: "1984",
        description:
            "A dystopian social science fiction novel by George Orwell set in a totalitarian regime ruled by the Party led by the omnipresent Big Brother.",
        price: 10.49,
        author: "George Orwell",
        genre: "Fiction",
        publisher: "Secker & Warburg",
        yearPublished: 1949,
        copiesSold: 30000000,
    },
    {
        ISBN: "978-1-5011-9729-1",
        name: "The Notebook",
        description:
            "A romance novel by Nicholas Sparks that follows the love story of Noah Calhoun and Allie Nelson, spanning decades as they face obstacles and reunite against all odds.",
        price: 9.99,
        author: "Nicholas Sparks",
        genre: "Romance",
        publisher: "Warner Books",
        yearPublished: 1996,
        copiesSold: 11000000,
    },
    {
        ISBN: "978-0-525-47809-7",
        name: "The Bourne Identity",
        description:
            "A thriller novel by Robert Ludlum that follows Jason Bourne, a man suffering from amnesia, as he tries to unravel his true identity and evade assassins.",
        price: 10.99,
        author: "Robert Ludlum",
        genre: "Action",
        publisher: "Richard Marek Publishers",
        yearPublished: 1980,
        copiesSold: 30000000,
    },
    {
        ISBN: "978-0-345-47651-4",
        name: "Mistborn: The Final Empire",
        description:
            "The first book in the Mistborn trilogy by Brandon Sanderson, set in a world where the Dark Lord has won and a group of rebels seeks to overthrow him using magic and intrigue.",
        price: 12.99,
        author: "Brandon Sanderson",
        genre: "Fantasy",
        publisher: "Tor Books",
        yearPublished: 2006,
        copiesSold: 500000,
    },
    {
        ISBN: "978-1-101-56084-2",
        name: "Divergent",
        description:
            "The first book in the Divergent trilogy by Veronica Roth, set in a future where society is divided into factions based on personality traits and following Tris Prior as she discovers her identity and fights against the system.",
        price: 10.99,
        author: "Veronica Roth",
        genre: "Action",
        publisher: "Katherine Tegen Books",
        yearPublished: 2011,
        copiesSold: 5000000,
    },
    {
        ISBN: "978-0-7653-1699-7",
        name: "The Way of Kings",
        description:
            "The first book in The Stormlight Archive series by Brandon Sanderson, set in the world of Roshar and following various characters as they navigate a world plagued by storms and war.",
        price: 14.99,
        author: "Brandon Sanderson",
        genre: "Fantasy",
        publisher: "Tor Books",
        yearPublished: 2010,
        copiesSold: 1000000,
    },
    {
        ISBN: "978-0-439-02348-1",
        name: "The Hunger Games",
        description:
            "The first book in The Hunger Games trilogy by Suzanne Collins, set in a dystopian future where the Capitol selects a boy and girl from the twelve districts to fight to the death on live television.",
        price: 8.99,
        author: "Suzanne Collins",
        genre: "Action",
        publisher: "Scholastic Press",
        yearPublished: 2008,
        copiesSold: 65000000,
    },
    {
        ISBN: "978-0-345-50595-0",
        name: "Red Rising",
        description:
            "The first book in the Red Rising series by Pierce Brown, set in a future where society is divided by color-coded castes, and following Darrow, a Red who infiltrates the elite Golds.",
        price: 11.99,
        author: "Pierce Brown",
        genre: "Action",
        publisher: "Del Rey Books",
        yearPublished: 2014,
        copiesSold: 500000,
    },
    {
        ISBN: "978-0-451-47885-5",
        name: "The Girl with the Dragon Tattoo",
        description:
            "A gripping thriller by Stieg Larsson that follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they investigate a decades-old disappearance linked to a wealthy family.",
        price: 11.49,
        author: "Stieg Larsson",
        genre: "Action",
        publisher: "Vintage Crime/Black Lizard",
        yearPublished: 2005,
        copiesSold: 30000000,
    },
    {
        ISBN: "978-1-4767-4657-4",
        name: "Me Before You",
        description:
            "A romance novel by Jojo Moyes that tells the story of Louisa Clark, a young woman who becomes a caregiver for Will Traynor, a quadriplegic man, and the unexpected bond that forms between them.",
        price: 10.99,
        author: "Jojo Moyes",
        genre: "Romance",
        publisher: "Pamela Dorman Books",
        yearPublished: 2012,
        copiesSold: 6000000,
    },
    {
        ISBN: "978-0-14-143974-7",
        name: "Treasure Island",
        description:
            "An adventure novel by Robert Louis Stevenson that follows young Jim Hawkins as he embarks on a journey to find treasure buried by the infamous pirate Captain Flint, encountering pirates, mutiny, and adventure along the way.",
        price: 8.99,
        author: "Robert Louis Stevenson",
        genre: "Adventure",
        publisher: "Penguin Classics",
        yearPublished: 1883,
        copiesSold: 15000,
    },
    {
        ISBN: "978-1-4472-9820-0",
        name: "Doctor Sleep",
        description:
            "A horror novel by Stephen King that follows the now-adult Dan Torrance, who must protect a young girl with similar powers from a cult known as The True Knot, who prey on children with psychic abilities.",
        price: 13.99,
        author: "Stephen King",
        genre: "Horror",
        publisher: "Hodder & Stoughton",
        yearPublished: 2013,
        copiesSold: 2000000,
    },
    {
        ISBN: "978-0-345-50025-2",
        name: "A Game of Thrones",
        description:
            "The first book in A Song of Ice and Fire series by George R.R. Martin, set in the fictional continents of Westeros and Essos and featuring political intrigue, war, and dragons.",
        price: 9.99,
        author: "George R.R. Martin",
        genre: "Fantasy",
        publisher: "Bantam Books",
        yearPublished: 1996,
        copiesSold: 6000000,
    },
    {
        ISBN: "978-0-446-31036-5",
        name: "The Da Vinci Code",
        description:
            "A mystery thriller novel by Dan Brown that follows symbologist Robert Langdon and cryptologist Sophie Neveu as they investigate a murder in Paris's Louvre Museum and discover a battle between the Priory of Sion and Opus Dei over the possibility of Jesus Christ having been married to Mary Magdalene.",
        price: 11.99,
        author: "Dan Brown",
        genre: "Mystery",
        publisher: "Doubleday",
        yearPublished: 2003,
        copiesSold: 80000000,
    },
    {
        ISBN: "978-1-4169-5479-9",
        name: "It",
        description:
            "A horror novel by Stephen King that follows a group of children as they confront an evil entity that takes the shape of a clown and terrorizes their town.",
        price: 12.99,
        author: "Stephen King",
        genre: "Horror",
        publisher: "Doubleday",
        yearPublished: 1986,
        copiesSold: 30000000,
    },
    {
        ISBN: "978-1-5011-0260-4",
        name: "The Fault in Our Stars",
        description:
            "A romance novel by John Green that follows the love story of Hazel Grace Lancaster, a sixteen-year-old cancer patient, and Augustus Waters, a fellow cancer survivor, as they navigate life and love.",
        price: 11.49,
        author: "John Green",
        genre: "Romance",
        publisher: "Dutton Books",
        yearPublished: 2012,
        copiesSold: 10000000,
    },
    {
        ISBN: "978-0-553-57340-3",
        name: "The Catcher in the Rye",
        description:
            "A novel by J.D. Salinger narrated by Holden Caulfield, a disaffected teenager who wanders through New York City after being expelled from prep school.",
        price: 11.49,
        author: "J.D. Salinger",
        genre: "Fiction",
        publisher: "Little, Brown and Company",
        yearPublished: 1951,
        copiesSold: 65000000,
    },
];
