name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      env:
        MONGO_URI: mongodb://localhost:27017/bookstore #from my understanding this will connect to the image being created
      run: npm test
